### ISSUE TITLE
"command: mas account" vs $PATH

### ISSUE THREAD

**Issue by basictheprogram** [geerlingguy/ansible-role-mas#27]
This task assume the command `mas` is in the $PATH
```yaml
- name: Get MAS account status
  command: mas account
  register: mas_account_result
  failed_when: mas_account_result.rc > 1
  check_mode: false
  changed_when: false
```
Using the role like below
```yaml
- hosts: localhost
  roles:
    - geerlingguy.homebrew
    - geerlingguy.mas
```
throws an exception, if I replace `mas` with `/usr/local/bin/mas` the error goes away.
```yaml
The full traceback is:
  File "/var/folders/tv/cdwkzld92t5bh0x4_y47mbyr0000gn/T/ansible_command_payload_502ytqym/ansible_command_payload.zip/ansible/module_utils/basic.py", line 2680, in run_command
    cmd = subprocess.Popen(args, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
fatal: [macos-ansible.cf.real-time.com]: FAILED! => {
    "changed": false,
    "cmd": "mas account",
    "failed_when_result": true,
    "invocation": {
        "module_args": {
            "_raw_params": "mas account",
            "_uses_shell": false,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "[Errno 2] No such file or directory: b'mas'",
    "rc": 2
}
```
I believe the command module does some sort of restricted shell?
